
  
version: "3.7"

services:
  db:
    build: .
    container_name: postgres-apiGo
    restart: unless-stopped
    tty: true
    ports:
      - "25432:5432"
    environment:
      POSTGRES_DB: api-tarefas
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: golang
      PGDATA: /var/lib/postgresql/data/webapi-mvc
    volumes:
      - webapi-mvc:/var/lib/postgresql/data

volumes:
  webapi-mvc: